# Site settings
title: ian delairre
author: Ian Delairre
author_avatar: https://avatars3.githubusercontent.com/u/9040652?v=3&s=460
email: idelairre@gmail.com
description: Blog for web development, computer science, philosophizing.
baseurl: "http://idelairre.github.io/" # optional
url: "https://github.com/idelairre"
twitter_username: idelairre
github_username: idelairre
github_repo: https://github.com/idelairre/idelairre.github.io
#google_analytics: UA-80085-YOUR-ID
disqus: idelairre

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap

paginate: 5
