# Site settings
title: ian delairre
author: Ian Delairre
author_avatar: https://gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=50
email: idelairre@gmail.com
description: Blog about whatever.
baseurl: "" # optional
url: "https://github.com/idelairre"
twitter_username: idelairre
github_username: idelairre
github_repo: https://github.com/idelairre/idelairre.github.io
#google_analytics: UA-80085-YOUR-ID
disqus: idelairre

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap

paginate: 5
